### ISSUE TITLE
A problem occured when I run test.sh

### ISSUE THREAD

**Issue by meisa233** [CodePothunter/CSPPT#1]
Hi!
I run your program in my computer.

`trans@trans-HVM-domU:~/scene_recognition/CSPPT$ bash test.sh
test.sh 
aaa
table: 0x40c9af88
/home/trans/torch/install/bin/luajit: ...ans/torch/install/share/lua/5.1/nn/ClassNLLCriterion.lua:43: attempt to index field 'output_tensor' (a nil value)
stack traceback:
	...ans/torch/install/share/lua/5.1/nn/ClassNLLCriterion.lua:43: in function 'updateOutput'
	...ch/install/share/lua/5.1/nngraph/ModuleFromCriterion.lua:20: in function 'func'
	/home/trans/torch/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
	/home/trans/torch/install/share/lua/5.1/nngraph/gmodule.lua:380: in function 'forward'
	./CSPPT/nets/lstm.lua:192: in function 'forward_testing'
	./CSPPT/nets/lstm.lua:281: in function 'evaluate'
	CSPPT/main.lua:165: in main chunk
	[C]: at 0x00405d50
`
How to solve it?
Thanks in advance!

**Comment by CodePothunter** [comment]
Hi, the reason is that this code was based on a very old version of the torch (Lua torch), which has been out of date. Nowadays, you can find many replacements. For example, try to use fairseq(https://github.com/pytorch/fairseq) for sequence labeling. 

Not suggest you run this old code, but thank you for your interest.

**Comment by meisa233** [comment]
> Hi, the reason is that this code was based on a very old version of the torch (Lua torch), which has been out of date. Nowadays, you can find many replacements. For example, try to use fairseq(https://github.com/pytorch/fairseq) for sequence labeling.
> 
> Not suggest you run this old code, but thank you for your interest.

Thanks for your prompt reply.
